name: Test configuration

on:
  push:
    branches: [master]

jobs:
  run-tests:
    name: Run all unit tests and generate coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install packages
        run: yarn install
      - name: Lint package
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Create coverage report
        run: yarn coverage
